title: CS Blog - sborquez 
description: > # this means to ignore newlines until "baseurl:"
  I am a computer science student at Federico Santa Maria Technical University.
  Posts about machine learning, digital image procesing, tutorials and research.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sborquez.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: sborkez #if your site has a twitter account, enter it here

# Author Settings
author: Sebastián Bórquez # add your name
author-img: sebastian-borquez.jpg # add your photo
about-author: I am a computer science student at Federico Santa Maria Technical University # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: sborquez # add your Github handle
social-linkedin: sborquez # add your Linkedin handle
social-email: sebastian.borquez.g@gmail.com # add your Email address

# Disqus
discus-identifier: sborquez # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
